//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogShowProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogOwner()
        {
            this.DogPassport = new HashSet<DogPassport>();
            this.Performance = new HashSet<Performance>();
        }
    
        public int IdDogOwner { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Pathronymic { get; set; }
        public string Gender { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public System.DateTime BirthdayDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DogPassport> DogPassport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performance { get; set; }
    }
}
