//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogShowProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogPassport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogPassport()
        {
            this.Dog = new HashSet<Dog>();
        }
    
        public int IdDogPassport { get; set; }
        public string NickName { get; set; }
        public System.DateTime LastDateVaccination { get; set; }
        public string Gender { get; set; }
        public System.DateTime BrithdayDate { get; set; }
        public string Breed { get; set; }
        public int IdDogOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dog> Dog { get; set; }
        public virtual DogOwner DogOwner { get; set; }
    }
}
