//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogShowWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int IdPerformance { get; set; }
        public int IdClub { get; set; }
        public int IdRing { get; set; }
        public int IdDogOwner { get; set; }
        public int IdDog { get; set; }
        public System.DateTime Date { get; set; }
        public string Award { get; set; }
        public int IdExpert { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Dog Dog { get; set; }
        public virtual DogOwner DogOwner { get; set; }
        public virtual Expert Expert { get; set; }
        public virtual Ring Ring { get; set; }
    }
}
